### YamlMime:ManagedReference
items:
- uid: Nomadik.Extensions.Swagger
  commentId: N:Nomadik.Extensions.Swagger
  id: Nomadik.Extensions.Swagger
  children:
  - Nomadik.Extensions.Swagger.NomadikIgnoreAttribute
  - Nomadik.Extensions.Swagger.NomadikOperationFilter
  - Nomadik.Extensions.Swagger.NomadikSearchAttribute
  - Nomadik.Extensions.Swagger.PropertyEnumSchema
  - Nomadik.Extensions.Swagger.SearchFilterAndSchema
  - Nomadik.Extensions.Swagger.SearchFilterOrSchema
  - Nomadik.Extensions.Swagger.SearchFilterSchema
  - Nomadik.Extensions.Swagger.SearchFilterWhereSchema
  - Nomadik.Extensions.Swagger.SearchOperationSchema
  - Nomadik.Extensions.Swagger.SearchOrderSchema
  - Nomadik.Extensions.Swagger.SearchQuerySchema
  - Nomadik.Extensions.Swagger.SwaggerGenOptionsExtensions
  langs:
  - csharp
  - vb
  name: Nomadik.Extensions.Swagger
  nameWithType: Nomadik.Extensions.Swagger
  fullName: Nomadik.Extensions.Swagger
  type: Namespace
  assemblies:
  - Nomadik.Extensions.Swagger
references:
- uid: Nomadik.Extensions.Swagger.NomadikIgnoreAttribute
  commentId: T:Nomadik.Extensions.Swagger.NomadikIgnoreAttribute
  href: Nomadik.Extensions.Swagger.NomadikIgnoreAttribute.html
  name: NomadikIgnoreAttribute
  nameWithType: NomadikIgnoreAttribute
  fullName: Nomadik.Extensions.Swagger.NomadikIgnoreAttribute
- uid: Nomadik.Extensions.Swagger.NomadikOperationFilter
  commentId: T:Nomadik.Extensions.Swagger.NomadikOperationFilter
  href: Nomadik.Extensions.Swagger.NomadikOperationFilter.html
  name: NomadikOperationFilter
  nameWithType: NomadikOperationFilter
  fullName: Nomadik.Extensions.Swagger.NomadikOperationFilter
- uid: Nomadik.Extensions.Swagger.NomadikSearchAttribute
  commentId: T:Nomadik.Extensions.Swagger.NomadikSearchAttribute
  href: Nomadik.Extensions.Swagger.NomadikSearchAttribute.html
  name: NomadikSearchAttribute
  nameWithType: NomadikSearchAttribute
  fullName: Nomadik.Extensions.Swagger.NomadikSearchAttribute
- uid: Nomadik.Extensions.Swagger.PropertyEnumSchema
  commentId: T:Nomadik.Extensions.Swagger.PropertyEnumSchema
  href: Nomadik.Extensions.Swagger.PropertyEnumSchema.html
  name: PropertyEnumSchema
  nameWithType: PropertyEnumSchema
  fullName: Nomadik.Extensions.Swagger.PropertyEnumSchema
- uid: Nomadik.Extensions.Swagger.SearchFilterAndSchema
  commentId: T:Nomadik.Extensions.Swagger.SearchFilterAndSchema
  href: Nomadik.Extensions.Swagger.SearchFilterAndSchema.html
  name: SearchFilterAndSchema
  nameWithType: SearchFilterAndSchema
  fullName: Nomadik.Extensions.Swagger.SearchFilterAndSchema
- uid: Nomadik.Extensions.Swagger.SearchFilterOrSchema
  commentId: T:Nomadik.Extensions.Swagger.SearchFilterOrSchema
  href: Nomadik.Extensions.Swagger.SearchFilterOrSchema.html
  name: SearchFilterOrSchema
  nameWithType: SearchFilterOrSchema
  fullName: Nomadik.Extensions.Swagger.SearchFilterOrSchema
- uid: Nomadik.Extensions.Swagger.SearchFilterSchema
  commentId: T:Nomadik.Extensions.Swagger.SearchFilterSchema
  href: Nomadik.Extensions.Swagger.SearchFilterSchema.html
  name: SearchFilterSchema
  nameWithType: SearchFilterSchema
  fullName: Nomadik.Extensions.Swagger.SearchFilterSchema
- uid: Nomadik.Extensions.Swagger.SearchFilterWhereSchema
  commentId: T:Nomadik.Extensions.Swagger.SearchFilterWhereSchema
  href: Nomadik.Extensions.Swagger.SearchFilterWhereSchema.html
  name: SearchFilterWhereSchema
  nameWithType: SearchFilterWhereSchema
  fullName: Nomadik.Extensions.Swagger.SearchFilterWhereSchema
- uid: Nomadik.Extensions.Swagger.SearchOperationSchema
  commentId: T:Nomadik.Extensions.Swagger.SearchOperationSchema
  href: Nomadik.Extensions.Swagger.SearchOperationSchema.html
  name: SearchOperationSchema
  nameWithType: SearchOperationSchema
  fullName: Nomadik.Extensions.Swagger.SearchOperationSchema
- uid: Nomadik.Extensions.Swagger.SearchOrderSchema
  commentId: T:Nomadik.Extensions.Swagger.SearchOrderSchema
  href: Nomadik.Extensions.Swagger.SearchOrderSchema.html
  name: SearchOrderSchema
  nameWithType: SearchOrderSchema
  fullName: Nomadik.Extensions.Swagger.SearchOrderSchema
- uid: Nomadik.Extensions.Swagger.SearchQuerySchema
  commentId: T:Nomadik.Extensions.Swagger.SearchQuerySchema
  href: Nomadik.Extensions.Swagger.SearchQuerySchema.html
  name: SearchQuerySchema
  nameWithType: SearchQuerySchema
  fullName: Nomadik.Extensions.Swagger.SearchQuerySchema
- uid: Nomadik.Extensions.Swagger.SwaggerGenOptionsExtensions
  commentId: T:Nomadik.Extensions.Swagger.SwaggerGenOptionsExtensions
  href: Nomadik.Extensions.Swagger.SwaggerGenOptionsExtensions.html
  name: SwaggerGenOptionsExtensions
  nameWithType: SwaggerGenOptionsExtensions
  fullName: Nomadik.Extensions.Swagger.SwaggerGenOptionsExtensions
